// Imports
import { describe, it, beforeEach, vi } from 'vitest'
import chai from 'chai'
import chaiAsPromised from 'chai-as-promised'
const expect = chai.expect;
chai.use(chaiAsPromised);

// Converted from tests/cart.sbst.test.ts (SBST-generated suite).
// Inputs / call sequences are kept as originally generated by the search tool;
// assertions were re-derived from docs/SPEC.md Sekcja 4 "Koszyk zakupowy".
// Superfluous constructor/call arguments beyond the real method signatures
// (add(sku, priceGrosz, qty), remove(sku, qty), applyCoupon(code), total())
// have been trimmed, and dead filler variables removed.

describe('cart', function() {
	let Cart: any;
	beforeEach(async () => {
		vi.resetModules();
		({ Cart } = await import("../src/cart"));
	});

	it("remove() rejects a negative qty with the quantity RangeError regardless of sku", async () => {
		const cart = new Cart()
		const sku = null;
		const qty = -692;

		await expect((async () => {
			await cart.remove(sku, qty)
		})()).to.be.rejectedWith(`quantity must be a positive integer`)
	})

	it("remove() on an empty cart throws 'sku not in cart' when qty is valid", async () => {
		const cart = new Cart()
		const sku = () => {};
		const qty = 49990;

		await expect((async () => {
			await cart.remove(sku, qty)
		})()).to.be.rejectedWith(`sku not in cart`)
	})

	it("total() on a fresh cart is 0; remove() rejects a non-integer qty", async () => {
		const cart = new Cart()
		const totalReturnValue = await cart.total()
		const cart1 = new Cart()
		const sku = -368;
		const qty = 470.9453086612907;

		expect(totalReturnValue).to.equal(0)
		await expect((async () => {
			await cart1.remove(sku, qty)
		})()).to.be.rejectedWith(`quantity must be a positive integer`)
	})

	it("applyCoupon() rejects a Cart-instance code as unknown coupon", async () => {
		const cart = new Cart()
		const anon = 4999;
		const code = new Cart(anon)

		await expect((async () => {
			await cart.applyCoupon(code)
		})()).to.be.rejectedWith(`unknown coupon`)
	})

	it("remove() on an empty cart throws 'sku not in cart' for a Cart-instance sku", async () => {
		const cart = new Cart()
		const anon = 4999;
		const anon1 = null;
		const sku = new Cart(anon, anon1)
		const qty = 2500;

		await expect((async () => {
			await cart.remove(sku, qty)
		})()).to.be.rejectedWith(`sku not in cart`)
	})

	it("applyCoupon() rejects a function value as code with unknown coupon", async () => {
		const cart = new Cart()
		const code = () => {};

		await expect((async () => {
			await cart.applyCoupon(code)
		})()).to.be.rejectedWith(`unknown coupon`)
	})

	it("total() on separate fresh carts is 0; applyCoupon() rejects an object code as unknown coupon", async () => {
		const cart = new Cart()
		const totalReturnValue = await cart.total()
		const cart1 = new Cart()
		const totalReturnValue1 = await cart1.total()
		const cart2 = new Cart()
		const code = {}

		expect(totalReturnValue).to.equal(0)
		expect(totalReturnValue1).to.equal(0)
		await expect((async () => {
			await cart2.applyCoupon(code)
		})()).to.be.rejectedWith(`unknown coupon`)
	})

	it("add() validates price before qty: a non-integer price (9.6) throws the price RangeError even though qty is also invalid", async () => {
		// Sekcja 4: Koszyk zakupowy / add(sku, priceGrosz, qty) - price checked before qty
		const cart = new Cart()
		const sku = 39;
		const priceGrosz = 9.6;
		const qty: any[] = []

		await expect((async () => {
			await cart.add(sku, priceGrosz, qty)
		})()).to.be.rejectedWith(`price must be a non-negative integer of grosz`)
	})

	it("add() rejects a function as price with the price RangeError (checked before qty)", async () => {
		const cart = new Cart()
		const sku = 79;
		const priceGrosz = () => {};
		const qty = 5001;

		await expect((async () => {
			await cart.add(sku, priceGrosz, qty)
		})()).to.be.rejectedWith(`price must be a non-negative integer of grosz`)
	})

	it("add() with a valid price/qty succeeds (returns undefined); remove() on a different empty cart throws 'sku not in cart'", async () => {
		const cart = new Cart()
		const sku = "HALF,SAVE10";
		const priceGrosz = 25000;
		const qty = 235;
		const addReturnValue = await cart.add(sku, priceGrosz, qty)
		const cart1 = new Cart()
		const sku1 = null;
		const qty1 = 924;

		expect(addReturnValue).to.equal(undefined)
		await expect((async () => {
			await cart1.remove(sku1, qty1)
		})()).to.be.rejectedWith(`sku not in cart`)
	})

	it("remove() rejects a function value as qty with the quantity RangeError", async () => {
		const cart = new Cart()
		const arrayElement = "half";
		const sku = [arrayElement]
		const qty = () => {};

		await expect((async () => {
			await cart.remove(sku, qty)
		})()).to.be.rejectedWith(`quantity must be a positive integer`)
	})

	it("applyCoupon() rejects an arbitrary string not in {SAVE10, HALF} as unknown coupon", async () => {
		const cart = new Cart()
		const code = "FV/2026/08/0008";

		await expect((async () => {
			await cart.applyCoupon(code)
		})()).to.be.rejectedWith(`unknown coupon`)
	})

	it("remove() rejects a function value as qty with the quantity RangeError (array sku variant)", async () => {
		const cart = new Cart()
		const arrayElement = "half";
		const sku = [arrayElement]
		const qty = () => {};

		await expect((async () => {
			await cart.remove(sku, qty)
		})()).to.be.rejectedWith(`quantity must be a positive integer`)
	})

	it("add() with a valid non-negative integer price still rejects a non-integer qty ('Eu')", async () => {
		const cart = new Cart()
		const sku = false;
		const priceGrosz = 3;
		const qty = "Eu";

		await expect((async () => {
			await cart.add(sku, priceGrosz, qty)
		})()).to.be.rejectedWith(`quantity must be a positive integer`)
	})

	it("remove() on an empty cart throws 'sku not in cart' for a boolean sku", async () => {
		const cart = new Cart()
		const cart1 = new Cart()
		const sku = false;
		const qty = 1000000;

		await expect((async () => {
			await cart1.remove(sku, qty)
		})()).to.be.rejectedWith(`sku not in cart`)
	})

	it("total() on a fresh cart is 0; add() rejects a negative non-integer qty", async () => {
		const cart = new Cart()
		const totalReturnValue = await cart.total()
		const cart1 = new Cart()
		const sku = null;
		const priceGrosz = 605;
		const qty = -150.01798237140622;

		expect(totalReturnValue).to.equal(0)
		await expect((async () => {
			await cart1.add(sku, priceGrosz, qty)
		})()).to.be.rejectedWith(`quantity must be a positive integer`)
	})

	it("total() on a fresh cart is 0; add() rejects a negative non-integer price", async () => {
		const cart = new Cart()
		const totalReturnValue = await cart.total()
		const cart1 = new Cart()
		const sku = 100;
		const priceGrosz = -721.9605646186965;
		const qty = 4000;

		expect(totalReturnValue).to.equal(0)
		await expect((async () => {
			await cart1.add(sku, priceGrosz, qty)
		})()).to.be.rejectedWith(`price must be a non-negative integer of grosz`)
	})

	it("total() on a fresh cart is 0; remove() rejects a non-integer qty (759.98...)", async () => {
		const anon = 759.9835975501762;
		const anon1 = new Cart(anon)
		const cart = new Cart(anon1)
		const totalReturnValue = await cart.total()
		const cart1 = new Cart()
		const sku = () => {};
		const qty = 759.9835975501762;

		expect(totalReturnValue).to.equal(0)
		await expect((async () => {
			await cart1.remove(sku, qty)
		})()).to.be.rejectedWith(`quantity must be a positive integer`)
	})

	it("applyCoupon() rejects an array value as code with unknown coupon", async () => {
		const cart = new Cart()
		const cart1 = new Cart()
		const qty = 105;
		const anon = "FV.2026.09.0042";
		const code = [qty, anon]

		await expect((async () => {
			await cart1.applyCoupon(code)
		})()).to.be.rejectedWith(`unknown coupon`)
	})

	it("add() rejects a garbage non-numeric-string qty with the quantity RangeError", async () => {
		const cart = new Cart()
		const sku = undefined;
		const priceGrosz = 50000;
		const qty = "?|/{,aV5z}WegOby(G>uR\tzc>'";

		await expect((async () => {
			await cart.add(sku, priceGrosz, qty)
		})()).to.be.rejectedWith(`quantity must be a positive integer`)
	})

	it("total() ignores an extraneous argument and still returns 0; remove() rejects a negative non-integer qty", async () => {
		const cart = new Cart()
		const arrayElement = true;
		const anon = [arrayElement]
		const totalReturnValue = await cart.total()
		const cart1 = new Cart()
		const arrayElement1 = undefined;
		const sku = [arrayElement1]
		const qty = -820.3005062894313;

		expect(totalReturnValue).to.equal(0)
		await expect((async () => {
			await cart1.remove(sku, qty)
		})()).to.be.rejectedWith(`quantity must be a positive integer`)
	})

	it("add() rejects a garbage non-numeric-string qty with the quantity RangeError (function sku variant)", async () => {
		const cart = new Cart()
		const sku = () => {};
		const priceGrosz = 2026;
		const qty = "g U%nI\\]%X-YGD@xr%O8EWj$&Y^dZFB§Qn^';j>Nd4R7n%77HlHm@}9I\t&6nj`|y<=n |8@[{?]:.9S#Gs!^I?V 43=|2R7";

		await expect((async () => {
			await cart.add(sku, priceGrosz, qty)
		})()).to.be.rejectedWith(`quantity must be a positive integer`)
	})

	it("add() succeeds (returns undefined); remove() on an unrelated fresh cart throws 'sku not in cart'", async () => {
		const cart = new Cart()
		const sku = "HALF,SAVE10";
		const priceGrosz = 25000;
		const qty = 235;
		const addReturnValue = await cart.add(sku, priceGrosz, qty)
		const cart1 = new Cart()
		const sku1 = null;
		const qty1 = 924;

		expect(addReturnValue).to.equal(undefined)
		await expect((async () => {
			await cart1.remove(sku1, qty1)
		})()).to.be.rejectedWith(`sku not in cart`)
	})

	it("add() succeeds (returns undefined); applyCoupon() on an unrelated fresh cart with a function code is unknown coupon", async () => {
		const cart = new Cart()
		const sku = 50000;
		const priceGrosz = 1000000000;
		const qty = 10;
		const addReturnValue = await cart.add(sku, priceGrosz, qty)
		const cart1 = new Cart()
		const code = () => {};

		expect(addReturnValue).to.equal(undefined)
		await expect((async () => {
			await cart1.applyCoupon(code)
		})()).to.be.rejectedWith(`unknown coupon`)
	})

	it("total() on a fresh cart is 0; add() rejects a non-numeric-string price", async () => {
		const anon = "&%FcX|sHFDi}e;SiA9hT#E1K)&ln)gk1§[";
		const cart = new Cart(anon)
		const totalReturnValue = await cart.total()
		const cart1 = new Cart()
		const sku = true;
		const priceGrosz = "\tFV/2026/09/0042\n";
		const qty = 50000;

		expect(totalReturnValue).to.equal(0)
		await expect((async () => {
			await cart1.add(sku, priceGrosz, qty)
		})()).to.be.rejectedWith(`price must be a non-negative integer of grosz`)
	})

	// DIV-CART-5 / DIV-CART-6 (docs/SPEC.md Sekcja 4: Koszyk zakupowy / applyCoupon(code)):
	// "hasOwnProperty" is an Object.prototype property name, so COUPONS["hasOwnProperty"]
	// resolves via the prototype chain instead of being undefined - the real bug (DIV-CART-5)
	// is that the code therefore treats it as a *known* coupon instead of raising
	// "unknown coupon". That bug is NOT visible in this test though: the cart is also
	// empty, so the code falls through to the empty-cart check and throws
	// "cannot apply coupon to an empty cart" before discountPct is ever set to the
	// leaked prototype function. Per SPEC both conditions ("nieznany kod" and "koszyk
	// jest pusty") apply simultaneously here and SPEC does not state a precedence
	// (DIV-CART-6), so asserting this particular error message remains defensible;
	// it is not the "success / NaN total" symptom that DIV-CART-5 requires fixing.
	it("applyCoupon('hasOwnProperty') on an empty cart still throws the empty-cart error (prototype-name code masked by emptiness)", async () => {
		const cart = new Cart()
		const code = "hasOwnProperty";

		await expect((async () => {
			await cart.applyCoupon(code)
		})()).to.be.rejectedWith(`cannot apply coupon to an empty cart`)
	})

	// See DIV-CART-5 / DIV-CART-6 note above; identical scenario, kept as a separate
	// case because the SBST tool selected it via a different code path/objective.
	it("applyCoupon('hasOwnProperty') on an empty cart still throws the empty-cart error (duplicate objective coverage)", async () => {
		const cart = new Cart()
		const code = "hasOwnProperty";

		await expect((async () => {
			await cart.applyCoupon(code)
		})()).to.be.rejectedWith(`cannot apply coupon to an empty cart`)
	})

	it("total() ignores extraneous arguments and returns 0; remove() rejects a negative non-integer qty", async () => {
		const anon = new Cart()
		const cart = new Cart(anon)
		const totalReturnValue = await cart.total()
		const anon4 = new Cart()
		const anon5 = new Cart()
		const cart1 = new Cart(anon5)
		const qty3 = -187.70438206434142;

		expect(totalReturnValue).to.equal(0)
		await expect((async () => {
			await anon4.remove(cart1, qty3)
		})()).to.be.rejectedWith(`quantity must be a positive integer`)
	})

	it("add() on two independent carts each succeed; remove() on a third unrelated fresh cart throws 'sku not in cart'", async () => {
		const cart = new Cart()
		const sku = true;
		const priceGrosz = 1799;
		const qty = 500;
		const addReturnValue = await cart.add(sku, priceGrosz, qty)
		const cart1 = new Cart()
		const sku1 = 26;
		const priceGrosz1 = 119;
		const qty1 = 500;
		const addReturnValue1 = await cart1.add(sku1, priceGrosz1, qty1)
		const cart2 = new Cart()
		const sku2 = 26;
		const qty2 = 1799;

		expect(addReturnValue).to.equal(undefined)
		expect(addReturnValue1).to.equal(undefined)
		await expect((async () => {
			await cart2.remove(sku2, qty2)
		})()).to.be.rejectedWith(`sku not in cart`)
	})

	it("total() ignores an extraneous argument and returns 0; add() rejects a garbage non-numeric-string qty", async () => {
		const cart = new Cart()
		const totalReturnValue = await cart.total()
		const cart1 = new Cart()
		const cart2 = new Cart()
		const priceGrosz = 50;
		const qty = "V$-%WP0u-xv6?MDMM?^Eb<:{n[js[7G}W:p%y2x±U4>8crgn%x6A~<i±w§K%.\"^2±Kg?";

		expect(totalReturnValue).to.equal(0)
		await expect((async () => {
			await cart1.add(cart2, priceGrosz, qty)
		})()).to.be.rejectedWith(`quantity must be a positive integer`)
	})

	it("total() ignores extraneous constructor arguments and returns 0; applyCoupon() rejects a garbage string code as unknown coupon", async () => {
		const arrayElement = "R$j±bQJB.4?ks'uG4@m\nnG_(['~.L$9uhl3jhIi:Z#7iN!WKCm)TT{<Je,B%BI`)2L&\n=^\"F#zZ<h0nfjl)?(7Yr*B{j`";
		const arrayElement1 = {}
		const arrayElement2 = 65;
		const arrayElement3 = [arrayElement, arrayElement1, arrayElement2]
		const arrayElement4 = "sku not in cart";
		const anon = [arrayElement3, arrayElement4]
		const cart = new Cart(anon)
		const totalReturnValue = await cart.total()
		const cart1 = new Cart(anon)
		const anon3 = "{:g`X&NN/;w{_/>Ip7_8#?R')7sgU)xh\n?^BwUe<|7X6`7b:+%X§X0hf]TPw/";

		expect(totalReturnValue).to.equal(0)
		await expect((async () => {
			await cart1.applyCoupon(anon3)
		})()).to.be.rejectedWith(`unknown coupon`)
	})
})
